* Introduction

This repo includes scripts for helping you solve some of the NYT
games.  Specifically:

|---------------+--------------|
| Script        | Puzzle       |
|---------------+--------------|
| lbsolver.py   | Letter Boxed |
| wdlysolver.py | Wordly       |
|---------------+--------------|

See the examples below.


* Requirements
This code has only been tested on =Ubuntu 24.04= runing under =WSL= on
a Windows 11 system.  Other operating systems may be more difficult
(like a native Windows 11 install, though =msys2= might provide a
solution).

The scrpits here use the python module [[https://github.com/jpuigcerver/openfst-python][openfst-python]] which can be
installed using =pip=.  The module installation downloads the [[https://www.openfst.org/twiki/bin/view/FST/WebHome][OpenFST
library]] source code and compiles it with the python extensions
enabled.

This can be accomplished using =conda= (=miniconda= or =Anaconda=) as
follows.  This only seems to work for me with Python version 3.6 or
3.7: 

#+begin_src bash
  conda create  -n pyfst python=3.7
  conda activate pyfst
  pip install openfst-python
#+end_src

Check the build requirements if you run into issues [[https://github.com/jpuigcerver/openfst-python][here]] (for example
you GCC installed).  

* Where to get a word list

** For =Letter Boxed= you can try =zyzzyva= from =scrabbleplayers.org=

One possible place to get a word list for Letter Boxed is from
=scrabbleplayers.org= by installing =zyzzyva=.  For example, follow
these steps and choose your local directory you create
=NASPAZyzzyva342/install= for the installation:

#+begin_src bash
  wget https://scrabbleplayers.org/zyzzyva/packages/342/NASPAZyzzyva342.zip
  mkdir NASPAZyzzyva342
  cd NASPAZyzzyva342
  unzip ../NASPAZyzzyva342.zip 
  mv 'Install NASPA Zyzzyva 3.4.2' Install_NASPA_Zyzzyva_3.4.2
  ./Install_NASPA_Zyzzyva_3.4.2 
#+end_src

The word list you want to use should be here:
=NASPAZyzzyva342/install/data/words/North-American/NSWL2023.txt=

The scrabble word list works pretty well with the NYT Letter Boxed
puzzles (but not perfectly).

** For =Wordle= you search around

For example, you could try [[https://wordletools.azurewebsites.net/weightedbottles][this one]] from =wordletools= or [[https://wordraiders.com/wordle-words/][this one]]
from =wordraiders=.  You can try out more
options by Googling for Worldle word lists.  The Scrabble dictionary
above doesn't work particularly well - you have to filter out the
output yourself.

* Letter Boxed Example
The =lbsolver.py= script usage is as follows:
#+begin_quote
usage: lbsolver.py [-h] [-v] -l LEFT -r RIGHT -t TOP -b BOTTOM -w WORD_LIST

Solve the NYT Letter Boxed puzzle using a word list

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         increase output verbosity
  -l LEFT, --left LEFT  Left edge of Letter Boxed puzzle
  -r RIGHT, --right RIGHT
                        Right edge of Letter Boxed puzzle
  -t TOP, --top TOP     Top edge of Letter Boxed puzzle
  -b BOTTOM, --bottom BOTTOM
                        Bottom edge of Letter Boxed puzzle
  -w WORD_LIST, --word-list WORD_LIST
                        Word list to use
#+end_quote

You just use the string of letters in the left, top, right and bottom of the
box for each of the =-l=, =-t=, =-r= and =-t= arguments (you can
actually mix them up and it won't matter) and you specify a word list.

For example, the following puzzle (from Dec 01 2025):

#+begin_quote
  LEFT:   C H O
  TOP:    P F N
  RIGHT:  A I T
  BOTTOM: R D L
#+end_quote

Would require the following command line arguments (using the above =zyzzyva= lexicon):
#+begin_src bash
  ./lbsolver.py -l CHO -t PFN -r AIT -b RDL \
                -w NASPAZyzzyva342/install/data/words/North-American/NSWL2023.txt \
                   > 01Dec2025-letter-boxed.txt
#+end_src

And the output looks like this:

#+begin_quote
  HANDCRAFT TOPICAL 12
  HANDCRAFT TRIPOLI 12
  PHILTRA AFICIONADA 12
  PHILTRA AFICIONADO 12
  HANDCLAP PORTFOLIO 12
  HANDICAP PORTFOLIO 12
  HANDICRAFT TOPICAL 12
  HANDICRAFT TRIPOLI 12
  HANDCRAFT TRIPLOID 12
  HANDCRAFT TRIPODAL 12
  HANDCRAFT TROPICAL 12
  HANDICRAFT TRIPLOID 12
  HANDICRAFT TRIPODAL 12
  HANDICRAFT TROPICAL 12
  PROLIFIC CANTHARIDIN 12
  AFICIONADA ANTHROPICAL 12
#+end_quote

The output is giving you the best sequences of single words and word
pairs by the number of unique letters they cover in the puzzle.  So in
this case, I could try and impress my family and friends with the two
word solutions =HANDCRAFT TROPICAL= (which concievably I could have
figured out) or =AFICIONADA ANTHROPICAL= (which I never would have
figured out).  I honestly think though it's best to wait until you've
tried to get a good solution yourself before running this script.
That is if you enjoy the puzzle.

* Wordle Example

So the syntax for the =wdlysolver.py= script is as follows:

#+begin_quote
usage: wdlysolver.py [-h] [-v] [-ex EX] [-c1 C1] [-c2 C2] [-c3 C3] [-c4 C4] [-c5 C5] -w WORD_LIST

Solve the NYT Letter Boxed puzzle using a word list

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         increase output verbosity
  -ex EX                Letters to exclude
  -c1 C1                Pattern to search for first letter of 5 letter for - only ".", "C", "^ADF" are supported
  -c2 C2                Pattern to search for first letter of 5 letter for - only ".", "C", "^ADF" are supported
  -c3 C3                Pattern to search for first letter of 5 letter for - only ".", "C", "^ADF" are supported
  -c4 C4                Pattern to search for first letter of 5 letter for - only ".", "C", "^ADF" are supported
  -c5 C5                Pattern to search for first letter of 5 letter for - only ".", "C", "^ADF" are supported
  -w WORD_LIST, --word-list WORD_LIST
                        Word list to use
#+end_quote

For letters which are solved in you puzzle, you just put the
letter. For example, if you know the 3rd letter is "A", use the
command line option =-c3 "A"=.  If one or more letters do
not occur in a given position, prefix them with the caret character
"^".  For example, if you know "C", "D" and "E" don't occur in
position 2, add the command line option =-c2 "^CDE"=.  Any letters you
have already ruled out should be added with the =-ex= option.  For
example if "F", "G", "H" and "I" do not occur in the solution, use the
command line option =-ex "FGHI"=.

I actually play =Wordly= on the Android which may have a very
different allowable lexicon than NYT Wordle.  Regardless, here's what
I get for the Wordly 01 Dec 2025 puzzle.  My first two guesses were
"RAISE" and "YOUTH" and I ended up with 4 letters all of which were in
the wrong place: "Y" was not in slot 1, "S" and "T" were not in slot 4
and E was not in slot 5.  The remaining letters "RAIOUH" were not in
the solution.  So I ran the =wdlysolver.py= script as follows:

#+begin_src bash
  ./wdlysolver.py -ex RAIOUH -c1 '^Y'  -c4 '^ST' -c5 '^E' -w <word-list>
#+end_src

Both the =wordletools= and =wordraiders= lists failed for me (no words
matched) while the Scrabble list gave me these interesting results, of
which I only really believed "BYTES" and "TYPES" would be accepted by
Wordly. I looked up a few of the other words like "WYTES" and "KYTES",
and according to Merriam-Webster they are "chiefly Scottish". Would
they really be allowed in a North American game of Scrabble?  Maybe
only if you can pull off a very convincing Scottish accent - and the
bar might not be too high among Americans listeners.

#+begin_quote
BYTES
WYTES
STYES
STYED
STEWY
TYNES
TYRES
TYPES
TYERS
TYEES
TYKES
TREYS
KYTES
#+end_quote

The solution ended up being "BYTES" (which I got after trying
"TYPES").

* Under the hood

** Letter Boxed

The Letter Boxed solver works by creating two FSTs.  The first "Letter
Boxed" FST is a grammar created from the puzzle of the day.  For a
given puzzle, the start node of the FST goes to any of the 12 letters
in the puzzle where each arc emits the corresponding letter.  Each
group of 3 letters from each side of puzzle can to any of the
remaining 9 letters on the other sides of the puzzle and arcs are
created for each of these transitions.  Finally, any of the letters in
the puzzle can also go directly to the end node.  So the "Letter
Boxed" FST is very much a cyclic graph.  All weights are set to "one"
for the arcs (that is the arcs have no cost).

A second FST is created from the input word list which we'll call the
"Lexicon" FST.  All words in the
list that are at least 3 letters long and only use the 12 letters in
the puzzle are kept.  These words are used to create a big "sausage
network" by taking each word, splitting it into it's component
letters and adding an arc with each letter as the input symbol and
=<epsilon>= as the output symbol with the exception of the very last
letter of the word which has the full word string as the output
symbol.  The final arc also uses a weight equal to negative the number
of unique letters in the word so that words that cover more of the 12
letters in the puzzle have a higher score.

Finally, we take the "Letter Boxed" FST and =compose= it with the
"Lexicon" FST creating an FST of all words in the lexicon that can be
parsed by the puzzle.  By taking the N shortest paths through the
puzzle, we can find the words that cover the most unique letters in
the puzzle.  

From there, we can create word pairs from the single words results by
joining words that share the same last and first letter and sort these
pairs by the number of unique.  One could accomplish the same thing by
creating a "Two Letter Lexicon" FST (by joining a copy of the
"Lexicon" FST onto the end of itself) and doing the composition again,
but I don't think you would end up with a different result. If one
were interested in 3 to 5 word solutions, you likely would want to use
an FST that represents these explicitly (for example by pasting up to
5 copies of the "Lexicon" FST end-to-end and adding a transition to
the final end node after each copy).  I was really only interested in
2 word solutions, but funky multi-word solutions could be fun as well.

** Wordle / Wordly
The wordle solver is a lot more straight forward.  Again two FSTs are
created, the first being a "Wordle" FST that has a sausage structure
composed of 5 linked FSTs (sausages) each of which only has parallel
arcs between two nodes. Each sausage links is created using all
letters in the alphabet excluding the ones in a user specified
exclusion pattern or they contain a single letter for the case where
the correct letter in a position is specified by the user.

The second FST is nearly identical to the "Lexicon" FST of the
previous example which matches sequences of letters at the input and
emits a single word at the output.  Only 5 letter words are considered
and only words that don't contain any excluded letters and do contain
letters that were specified in a positional pattern.

Again the composition of the two FSTS yields a list of possible
solutions to the puzzle.  The quality of the output will rely heavily
on the word lexicon you use.
